# Generated by Django 3.2.7 on 2021-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('serving_size', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('calories_from_fat', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugars', models.FloatField()),
                ('protein', models.FloatField()),
            ],
        ),
    ]
